Fixed mobile responsive css bugs
limseung1/coursescheduler pull request #70
Opened 2023-05-01 05:28 UTC by rdick

What?
1. Fixed spelling mistake in DialogDragDrop.tsx
Before
![image](https://user-images.githubusercontent.com/62073529/235407669-2aef879e-9f6a-4f63-a355-e37ddce2895b.png)
After
![image](https://user-images.githubusercontent.com/62073529/235407623-b80451d2-7536-4735-a399-f3c936711552.png)

2. Made mobile responsive mobile fonts for timeslots at 
Before
![image](https://user-images.githubusercontent.com/62073529/235407701-4cded7ca-2675-48ed-85c0-fc9d0ea0dfe2.png)

After
![image](https://user-images.githubusercontent.com/62073529/235407729-beab0a3f-3841-4ccc-8fe0-b945af2cc22a.png)

3. Fixed Course Panel so seat numbers don't go outside of panel

Before
![image](https://user-images.githubusercontent.com/62073529/235407816-ef7cce2f-428b-4d04-9b72-5345876e451c.png)

After
![image](https://user-images.githubusercontent.com/62073529/235407844-f52fac95-6cff-4d10-a731-4d115d8e2c0e.png)

4. Tooltip overlaps Dialog
before 
![image](https://user-images.githubusercontent.com/62073529/235408489-1746b685-53a3-427b-83f8-2d4c8b49f087.png)

after
![image](https://user-images.githubusercontent.com/62073529/235409268-b3925e3f-4558-47a2-90da-365c50a7d3f6.png)

5. Generate Course Tooltip Is Now Placed Below Button on Mobile View
Before
![image](https://user-images.githubusercontent.com/62073529/235409326-16f7fc72-faaa-4e9d-9151-7d8a412152be.png)

After
![image](https://user-images.githubusercontent.com/62073529/235409350-ccd8b2cd-5793-4715-9543-5a92a214ae9d.png)

Testing?

Tested all of these bugs to see if they were fixed

2023-05-01 20:09 UTC, limseung1 requested changes

2023-05-01 20:09 UTC, limseung1 commented on src/components/dialog/DialogDragDrop.tsx
I would prefer if you kept it time slot, instead of class. See https://www.goramp.com/blog/what-is-time-slot-management for how we refer to time slot a time slot.

2023-05-01 20:09 UTC, limseung1 commented on src/components/coursesearch/5. DialogClassesFull.tsx
why does zIndex need to be 1501? I know z index has be higher than the dialog, but 1501 seems excessive.

2023-05-01 20:09 UTC, limseung1 commented on src/components/dialog/TooltipInstruction.tsx
Thanks for making a helper for the placement of the tooltip. Good work.

2023-05-01 20:09 UTC, limseung1 commented on src/components/coursesearch/3. ClassInfo.tsx
Nice job on removing inline styling

2023-05-01 20:09 UTC, limseung1 commented on src/components/coursesearch/1. SearchPanel.tsx
Why do we include chips? I thought we are settling with turning off generate btn when empty class list.

2023-05-01 20:13 UTC, rdick commented on src/components/coursesearch/5. DialogClassesFull.tsx
Tooltip is z index of 1500. Dialog needs to be zIndex of 1501 to be more than it.

2023-05-01 20:16 UTC, rdick commented on src/components/coursesearch/1. SearchPanel.tsx
I think we agreed on chips and turning off the generate button. How is a user supposed to delete a course (that is in the queue) if they don't want it?

2023-05-03 23:48 UTC, limseung1 approved these changes

2023-05-04 04:01 UTC, merged